/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shinhoandroid_testjni_JNITest */

#ifndef _Included_com_shinhoandroid_testjni_JNITest
#define _Included_com_shinhoandroid_testjni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shinhoandroid_testjni_JNITest
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shinhoandroid_testjni_JNITest_getStr
  (JNIEnv *, jclass);

/*
 * Class:     com_shinhoandroid_testjni_JNITest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_shinhoandroid_testjni_JNITest_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
